
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/Users/api/odin/"
      - "/Users/api/.codeium/windsurf/bin/"
      - "/opt/homebrew/opt/llvm/bin/"
      - "/Users/api/go/bin/"
      - "/opt/local/sbin/"
      - "/opt/local/bin/"
      - "/Applications/Unity/accelerator/"
      - "/Applications/Sublime Text.app/Contents/SharedSupport/bin/"
      - "/Users/api/.local/bin/"
      - "/Users/api/Library/pnpm/"
      - "/opt/homebrew/bin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/Library/Apple/usr/bin/"
      - "/Applications/VMware Fusion.app/Contents/Public/"
      - "/usr/local/share/dotnet/"
      - "/Users/api/.dotnet/tools/"
      - "/Library/TeX/texbin/"
      - "/Users/api/.cargo/bin/"
      - "/Users/api/.local/share/nvm/v22.12.0/bin/"
      - "/Users/api/.deno/bin/"
    searched_directories:
      - "/Users/api/odin/uname"
      - "/Users/api/.codeium/windsurf/bin/uname"
      - "/opt/homebrew/opt/llvm/bin/uname"
      - "/Users/api/go/bin/uname"
      - "/opt/local/sbin/uname"
      - "/opt/local/bin/uname"
      - "/Applications/Unity/accelerator/uname"
      - "/Applications/Sublime Text.app/Contents/SharedSupport/bin/uname"
      - "/Users/api/.local/bin/uname"
      - "/Users/api/Library/pnpm/uname"
      - "/opt/homebrew/bin/uname"
      - "/usr/local/bin/uname"
      - "/System/Cryptexes/App/usr/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/Users/api/odin"
        - "/Users/api/.codeium/windsurf/bin"
        - "/opt/homebrew/opt/llvm/bin"
        - "/Users/api/go/bin"
        - "/opt/local/sbin"
        - "/opt/local/bin"
        - "/Applications/Unity/accelerator"
        - "/Applications/Sublime Text.app/Contents/SharedSupport/bin"
        - "/Users/api/.local/bin"
        - "/Users/api/Library/pnpm"
        - "/opt/homebrew/bin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/Library/Apple/usr/bin"
        - "/Applications/VMware Fusion.app/Contents/Public"
        - "/usr/local/share/dotnet"
        - "~/.dotnet/tools"
        - "/Library/TeX/texbin"
        - "/Users/api/.cargo/bin"
        - "/Users/api/.local/share/nvm/v22.12.0/bin"
        - "/Users/api/.deno/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 24.6.0 - arm64
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/Platform/Darwin.cmake:76 (find_program)"
      - "/opt/homebrew/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:32 (include)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_INSTALL_NAME_TOOL"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "install_name_tool"
    candidate_directories:
      - "/Users/api/odin/"
      - "/Users/api/.codeium/windsurf/bin/"
      - "/opt/homebrew/opt/llvm/bin/"
      - "/Users/api/go/bin/"
      - "/opt/local/sbin/"
      - "/opt/local/bin/"
      - "/Applications/Unity/accelerator/"
      - "/Applications/Sublime Text.app/Contents/SharedSupport/bin/"
      - "/Users/api/.local/bin/"
      - "/Users/api/Library/pnpm/"
      - "/opt/homebrew/bin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/Library/Apple/usr/bin/"
      - "/Applications/VMware Fusion.app/Contents/Public/"
      - "/usr/local/share/dotnet/"
      - "/Users/api/.dotnet/tools/"
      - "/Library/TeX/texbin/"
      - "/Users/api/.cargo/bin/"
      - "/Users/api/.local/share/nvm/v22.12.0/bin/"
      - "/Users/api/.deno/bin/"
    searched_directories:
      - "/Users/api/odin/install_name_tool"
      - "/Users/api/.codeium/windsurf/bin/install_name_tool"
      - "/opt/homebrew/opt/llvm/bin/install_name_tool"
      - "/Users/api/go/bin/install_name_tool"
      - "/opt/local/sbin/install_name_tool"
      - "/opt/local/bin/install_name_tool"
      - "/Applications/Unity/accelerator/install_name_tool"
      - "/Applications/Sublime Text.app/Contents/SharedSupport/bin/install_name_tool"
      - "/Users/api/.local/bin/install_name_tool"
      - "/Users/api/Library/pnpm/install_name_tool"
      - "/opt/homebrew/bin/install_name_tool"
      - "/usr/local/bin/install_name_tool"
      - "/System/Cryptexes/App/usr/bin/install_name_tool"
    found: "/usr/bin/install_name_tool"
    search_context:
      ENV{PATH}:
        - "/Users/api/odin"
        - "/Users/api/.codeium/windsurf/bin"
        - "/opt/homebrew/opt/llvm/bin"
        - "/Users/api/go/bin"
        - "/opt/local/sbin"
        - "/opt/local/bin"
        - "/Applications/Unity/accelerator"
        - "/Applications/Sublime Text.app/Contents/SharedSupport/bin"
        - "/Users/api/.local/bin"
        - "/Users/api/Library/pnpm"
        - "/opt/homebrew/bin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/Library/Apple/usr/bin"
        - "/Applications/VMware Fusion.app/Contents/Public"
        - "/usr/local/share/dotnet"
        - "~/.dotnet/tools"
        - "/Library/TeX/texbin"
        - "/Users/api/.cargo/bin"
        - "/Users/api/.local/share/nvm/v22.12.0/bin"
        - "/Users/api/.deno/bin"
      CMAKE_INSTALL_PREFIX: "/usr/local"
...
