include("/Users/api/FastNoise2/cmake/CPM.cmake")
CPMAddPackage("NAME;corrade;GITHUB_REPOSITORY;mosra/corrade;GIT_TAG;295bbba1f49887da060465f88b8501965f6acd7d;GIT_SUBMODULES;src;EXCLUDE_FROM_ALL;YES;OPTIONS;CORRADE_BUILD_STATIC ON;CORRADE_BUILD_STATIC_UNIQUE_GLOBALS OFF;CORRADE_MSVC_COMPATIBILITY ON;CORRADE_WITH_INTERCONNECT OFF;CORRADE_WITH_TESTSUITE OFF")
set(corrade_FOUND TRUE)